// export const FETCH_PROJECTS_BEGIN = 'FETCH_PROJECTS_BEGIN'
// export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS'
// export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE'

export const SET_MAIN_NAME = 'SET_MAIN_NAME';

export const SET_LOADING = 'SET_LOADING'